[package]
name = "spotifyclt"
version = "0.1.0"
authors = ["billiob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.10"
clap = "2.33"
